# Generated by Django 5.1 on 2024-08-26 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='L',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='M',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='S',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='XL',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
