# Generated by Django 5.1 on 2024-09-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cropping',
        ),
    ]
