# Generated by Django 5.1 on 2024-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productimage_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
